name: Test
on:
  push:
    paths:
      - 'nari/**.py'
  pull_request:
    paths:
      - 'nari/**.py'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Pip list
      run: pip list -v

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages
        key: ${{ hashFiles('setup.py') }}
        restore-keys: setup.py

    - name: pylint
      run: pylint nari
  tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Pip list
      run: pip list -v

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages
        key: ${{ hashFiles('setup.py') }}
        restore-keys: setup.py

    - name: unittest
      run: python -munittest
  types:
    name: check types
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Pip list
      run: pip list -v

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages
        key: ${{ hashFiles('setup.py') }}
        restore-keys: setup.py
    - name: mypy
      run: mypy nari
